-- Future: server-side monitoring
-- CREATE TABLE monitors (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     bookmark_name VARCHAR NOT NULL,
--     polygon GEOMETRY(POLYGON, 4326) NOT NULL,
--     product VARCHAR DEFAULT 'NDVI',
--     min_cloud_cover FLOAT DEFAULT 30,
--     last_checked TIMESTAMPTZ,
--     last_result VARCHAR,
--     active BOOLEAN DEFAULT true,
--     created_at TIMESTAMPTZ DEFAULT now()
-- );
